packageExtensions:
  "@firebase/app-types@*":
    dependencies:
      "@firebase/logger": "*"
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  firebase-functions@*:
    dependencies:
      "@types/express-serve-static-core": "4.17.1"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
